### ISSUE TITLE
Add a Code Editor in one side

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/tic-tac-toe#2]
Use Ace Editor with JavaScript syntax highlighting to add in the game.
Refer angry-coders repository to do this.

**Comment by 0xnmn** [comment]
I have completed the tic tac toe game with all the features. Including editor. Everything working fine. 
Test live [here](http://namankumar.me/ttt/)
Repo: https://github.com/hereisnaman/ttt
Can’t fork your repo. please pull.

## Screenshots:
![image](https://cloud.githubusercontent.com/assets/22571395/26273027/a2f49de2-3d44-11e7-8c17-249bfdd2937d.png)

![image](https://cloud.githubusercontent.com/assets/22571395/26273029/a7eeae46-3d44-11e7-96ca-4fcde782b9ff.png)
