### ISSUE TITLE
Algorithm for the Game

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/tic-tac-toe#3]
Implement the game logic/ algorithm, to fill the cell with X after player every player move with 0.

Game should work in 2 modes ( Give a toggle button ) to choose the algorithm.

1) Random Algorithm -Algorithms chooses any random position (empty)

2) Smart Algorithm - Algorithm chooses the best possible opponent move. 

Player has to write the algorithm in the beginning and all subsequent moves will be computed by players algorithm.

**Comment by asutosh7hota** [comment]
I would love to have some clarification on the issue, like, are we going to make a bot for the game(Computer player) for the smart mode ?

**Comment by 0xnmn** [comment]
@asutosh7hota Yes we are. one with just random computer turn and one with smart turn.

**Comment by asutosh7hota** [comment]
I would like to work on this issue if @hereisnaman or someone else is not working on it?

**Comment by 0xnmn** [comment]
@asutosh7hota actually I have added some features but have not submitted the PR. I am done with random and 2 player game mode. There are updates in the script. In some time I'll submit the pr. Then you can work on the smart algo portion. It would be great to work in collaboration. 

I'll notify you.

Thanks for showing interest.

**Comment by asutosh7hota** [comment]
@hereisnaman  Great going man! I would love to contribute in the later part after you push the update work.

**Comment by 0xnmn** [comment]
completed: https://github.com/coding-blocks/tic-tac-toe/pull/7
